name: DynamoDB Local Testing

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    env:  # Define environment variables here
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: ap-northeast-1
      DYNAMODB_ENDPOINT: http://localhost:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'

      - name: Create table 1
        run: aws dynamodb create-table --cli-input-json file://${{ github.workspace }}/.github/workflows/test-table-1.json --endpoint-url http://localhost:8000
        
      - name: Create table 2  
        run: aws dynamodb create-table --cli-input-json file://${{ github.workspace }}/.github/workflows/test-table-2.json --endpoint-url http://localhost:8000

      - name: Describe table 1
        run: aws dynamodb describe-table --table-name test-table-1 --endpoint-url http://localhost:8000

      - name: Describe table 2
        run: aws dynamodb describe-table --table-name test-table-2 --endpoint-url http://localhost:8000


      - name: Run tests
        run: go test ./... -v
